name: deploy-on-s3

on:
  push:
    branches: [ master ]
    
jobs:
  deploy:
    runs-on: self-hosted
       #CLOUDFRONT_ID: ${{secrets.CLOUDFRONT_ID}}
    steps:
    - uses: actions/checkout@master
    - name: copy to s3 
      run: |
       aws s3 sync . "$AWS_S3_BUCKET"
       echo "file Updated"
      env:
       AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
       AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
       AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }} 
     #  aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_ID" --paths '/*'
     #  echo "Website updated"
  #  - name: Invalidation request   
   #   run: |..
         

      
